Try to fix the TinyMCE heisenbug.
It happens in the afterEach method when $('body').empty() is called and
apparently has to do with TinyMCE itself not being properly cleared.

TypeError: 'undefined' is not an object (evaluating 'doc.createRange')
(/home/jc/buildout.coredev/src/mockup/mockup/bower_components/tinymce-builded/js/tinymce/tinymce.js